### ISSUE TITLE
Node-gyp rebuild fails due to failing dependency to sse4_crc32@3.4.0

### ISSUE THREAD

**Issue by zaoudis** [albertorestifo/gulp-gcloud-publish#1]
With node v4.2.1 sse4_crc32@3.4.0 installation fails so node-gyp rebuild fails so gulp-gcloud-publish can't be installed too.

If you run npm install sse4_crc32@v4.1.0 then node-gyp rebuild is successfully installed so you probably need to update that dependency in order to make this work for node 4

**Comment by albertorestifo** [comment]
Thanks for the report!

d0ba29190aeef9d7161e782c5bc873564ef1231c Dependencies have been updated with a bump to `v1.2.0` and the build passed
